-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 13:52:47 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dolphin_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dolphin_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dolphin_db` DEFAULT CHARACTER SET utf8 ;
USE `dolphin_db` ;

-- -----------------------------------------------------
-- Table `dolphin_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dolphin_db`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` TEXT(255) NULL,
  `created_at` TIMESTAMP(6) NULL,
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dolphin_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dolphin_db`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `role_id` INT UNSIGNED NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` TEXT(255) NOT NULL,
  `created_at` TIMESTAMP(6) NULL,
  `updated_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `roles_user_id_idx` (`role_id` ASC),
  CONSTRAINT `roles_user_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `dolphin_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dolphin_db`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dolphin_db`.`news` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `heading` VARCHAR(45) NULL,
  `body` LONGTEXT NULL,
  `created_at` TIMESTAMP(6) NULL,
  `updated_at` TIMESTAMP(6) NULL,
  `user_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `news_user_id_idx` (`user_id` ASC),
  CONSTRAINT `news_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `dolphin_db`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dolphin_db`.`diciplins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dolphin_db`.`diciplins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dolphin_db`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dolphin_db`.`scores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `diciplin_id` INT UNSIGNED NULL,
  `user_id` INT UNSIGNED NULL,
  `type` TINYINT(1) NULL,
  `time` DOUBLE NULL,
  `created_at` TIMESTAMP(6) NULL,
  PRIMARY KEY (`id`),
  INDEX `scores_user_id_idx` (`user_id` ASC),
  INDEX `diciplins_scores_id_idx` (`diciplin_id` ASC),
  CONSTRAINT `scores_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `dolphin_db`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `diciplin_score_id`
    FOREIGN KEY (`diciplin_id`)
    REFERENCES `dolphin_db`.`diciplins` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dolphin_db`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dolphin_db`.`payments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NULL,
  `created_at` TIMESTAMP(6) NULL,
  `updated_at` TIMESTAMP(6) NULL,
  `user_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `payment_user_id_idx` (`user_id` ASC),
  CONSTRAINT `payment_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `dolphin_db`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
